version: '2'
services:
  kiss-playback:
    container_name: kiss-playback
    build: .
    ports:
     - "8000:8000"
    networks:
        vcc:
            ipv4_address: 10.0.0.2

networks:
    vcc:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.0.0.0/24
              gateway: 10.0.0.1
